SEQ_ARG:
  # ID 和 模板序列为用户必填项
  SEQUENCE_ID: BRCA2_SEGMENT
  SEQUENCE_TEMPLATE: GTGGCGCGAGCTTCTGAAACTAGGCGGCAGAGGCGGAGCCGCTGTGGCACTGCTGCGCCTCTGCTGCGCCTCGGGTGTCTTTTGCGGCGGTGGGTCGCCGCCGGGAGAAGCGTGAGGGGACAGATTTGTGACCGGCGCGGTTTTTGTCAGCTTACTCCGGCCAAAAAAGAACTGCACCTCTGGAGCGGGTTAGTGGTGGTGGTAGTGGGT
  # SEQ excluded range(第一个是位置 第二个参数是长度)
  SEQUENCE_EXCLUDED_REGIONSEQUENCE_EXCLUDED_REGION: []
  # SEQUENCE_PRIMER_PAIR_OK_REGION_LIST: []
  # SEQUENCE_PRIMER_PAIR_OK_REGION_LIST: [[50,50,150,50]]

GLOBAL_ARG:
  # NUM return
  PRIMER_NUM_RETURN: 10
  # SIZE range
  PRIMER_OPT_SIZE: 20
  PRIMER_MIN_SIZE: 15
  PRIMER_MAX_SIZE: 30
  #  TM range
  PRIMER_OPT_TM: 60.0
  PRIMER_MIN_TM: 40.0
  PRIMER_MAX_TM: 65.0
  #  GC range
  PRIMER_MIN_GC : 30.0
  PRIMER_MAX_GC : 70.0
  # PROD
  PRIMER_PRODUCT_SIZE_RANGE: [[150,150],[125,150]]